// Copyright 1998-2018 Epic Games, Inc. All Rights Reserved.

using UnrealBuildTool;
using System.Collections.Generic;
using System.IO;
using System.Diagnostics;

public class ShooterGame : ModuleRules
{
	// Path to ISPC compiler binary.
	public static readonly string ISPCExe = "E:\\ispc-v1.9.2-windows\\ispc.exe";

	// Flags with which to compile ISPC source.
	public static readonly string ISPCFlags = "-g --target=sse4-i32x4"; // FIXME

	// ISPC sources to build and link.
	public static readonly string[] ISPCSources = new string[]
	{
		"Private/ISPC/Kernels.ispc",
	};

	// Accessors to autogenerated rule details.
	public static string[] ISPCAbsoluteSources { get { return _ISPCAbsoluteSources; } }
	public static string[] ISPCObjects { get { return _ISPCObjects; } }
	public static string[] ISPCHeaders { get { return _ISPCHeaders; } }

	// Containers for autogenerated rule details.
	private static string[] _ISPCAbsoluteSources;
	private static string[] _ISPCObjects;
	private static string[] _ISPCHeaders;

	// Guard to make sure that the target has been correctly set up.
	private static bool bISPCHasBeenSetupInTarget = false;

	// Sets up ISPC build rules as custom pre-build step in the passed in target, and caches autogenerated rule details.
	public static void SetupISPCRules(TargetRules Target)
	{
		string ModuleName = new StackFrame().GetMethod().DeclaringType.ToString();

		string PlatformIntermediateDir = Path.Combine
		(
			Target.ProjectFile.Directory.FullName,
			"Intermediate",
			"Build",
			Target.Platform.ToString(),
			/*UEBuildPlatform.GetBuildPlatform(Target.Platform).GetFolderNameForArchitecture*/(Target.Architecture)
		);

		string ModuleSourceDirectory = Path.Combine
		(
			Target.ProjectFile.Directory.FullName,
			"Source",
			ModuleName
		);
		Debug.Assert(File.Exists(Path.Combine(ModuleSourceDirectory, ModuleName + ".Build.cs")), string.Format("`ModuleSourceDirectory` needs to point at the `Source` directory of module `{0}`", ModuleName));

		string ObjectDir = Path.Combine
		(
			PlatformIntermediateDir,
			Target.Name,
			Target.Configuration.ToString(),
			ModuleName
		);

		string HeaderDir = Path.Combine
		(
			PlatformIntermediateDir,
			Target.Type == TargetType.Editor ? "UE4Editor" : "UE4",
			"Inc",
			ModuleName
		);

		Directory.CreateDirectory(ObjectDir);
		Directory.CreateDirectory(HeaderDir);

		List<string> AbsoluteSources = new List<string>();
		List<string> Objects = new List<string>();
		List<string> Headers = new List<string>();
		foreach (string RelativeSource in ISPCSources)
		{
			string Source = Path.Combine(ModuleSourceDirectory, RelativeSource);
			string BaseName = Path.GetFileName(RelativeSource);
			string Object = Path.Combine(ObjectDir, BaseName.Replace(".ispc", ".ispc.o"));
			string Header = Path.Combine(HeaderDir, BaseName.Replace(".ispc", ".ispc.h"));
			AbsoluteSources.Add(Source);
			Objects.Add(Object);
			Headers.Add(Header);
			Target.PreBuildSteps.Add(string.Format("\"{0}\" \"{1}\" -o \"{2}\" -h \"{3}\" {4}",
				ISPCExe,
				Source,
				Object,
				Header,
				ISPCFlags
				));
		}
		_ISPCAbsoluteSources = AbsoluteSources.ToArray();
		_ISPCObjects = Objects.ToArray();
		_ISPCHeaders = Headers.ToArray();

		bISPCHasBeenSetupInTarget = true;
	}

	// Sets up module rules from cached autogenerated ISPC rules.
	private void SetModuleRulesFromISPC(ReadOnlyTargetRules Target)
	{
		Debug.Assert(bISPCHasBeenSetupInTarget, string.Format("`{0}.SetupISPCRules(this);` needs to be called first from target {1}", GetType().ToString(), Target.Name));
		ExternalDependencies.AddRange(ISPCAbsoluteSources);
		ExternalDependencies.AddRange(ISPCObjects);
		ExternalDependencies.AddRange(ISPCHeaders);
		PublicAdditionalLibraries.AddRange(ISPCObjects);
	}

	public ShooterGame(ReadOnlyTargetRules Target) : base(Target)
	{
		SetModuleRulesFromISPC(Target);

		PrivateIncludePaths.AddRange(
			new string[] { 
				"ShooterGame/Classes/Player",
				"ShooterGame/Private",
				"ShooterGame/Private/UI",
				"ShooterGame/Private/UI/Menu",
				"ShooterGame/Private/UI/Style",
				"ShooterGame/Private/UI/Widgets",
            }
		);

        PublicDependencyModuleNames.AddRange(
			new string[] {
				"Core",
				"CoreUObject",
				"Engine",
				"OnlineSubsystem",
				"OnlineSubsystemUtils",
				"AssetRegistry",
                "AIModule",
				"GameplayTasks",
			}
		);

        PrivateDependencyModuleNames.AddRange(
			new string[] {
				"InputCore",
				"Slate",
				"SlateCore",
				"ShooterGameLoadingScreen",
				"Json",
				"ApplicationCore"
			}
		);

		DynamicallyLoadedModuleNames.AddRange(
			new string[] {
				"OnlineSubsystemNull",
				"NetworkReplayStreaming",
				"NullNetworkReplayStreaming",
				"HttpNetworkReplayStreaming",
				"LocalFileNetworkReplayStreaming"
			}
		);

		PrivateIncludePathModuleNames.AddRange(
			new string[] {
				"NetworkReplayStreaming"
			}
		);
	}
}
