// Autogenerated by GenerateCallbackMacros.py, do not modify.
#pragma once

#include "CppInterop.h"

#ifdef ISPC
	#define _CppCallbackTemplate(FuncName, ArgDeclVarying, ArgDeclUniform, ArgFwd)	\
		inline void FuncName ArgDeclVarying	\
		{	\
			extern "C" void FuncName ## _CppCallback ArgDeclUniform;	\
			foreach_active (Index)	\
			{	\
				FuncName ## _CppCallback ArgFwd;	\
			}	\
		}

	#define _CppCallbackTemplate_RetVal(ReturnType, FuncName, ArgDeclVarying, ArgDeclUniform, ArgFwd)	\
		inline ReturnType varying FuncName ArgDeclVarying	\
		{	\
			extern "C" ReturnType uniform FuncName ## _CppCallback ArgDeclUniform;	\
			ReturnType varying ReturnValue;	\
			foreach_active (Index)	\
			{	\
				ReturnValue = insert(ReturnValue, Index, FuncName ## _CppCallback ArgFwd);	\
			}	\
		}

	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		_CppCallbackTemplate(FuncName, (), (), ())
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0), (ArgType0 uniform Arg0), (extract(Arg0, Index)))
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1), (ArgType0 uniform Arg0, ArgType1 uniform Arg1), (extract(Arg0, Index), extract(Arg1, Index)))
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index)))
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index)))
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index)))
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index)))
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index)))
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (), (), ())
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0), (ArgType0 uniform Arg0), (extract(Arg0, Index)))
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1), (ArgType0 uniform Arg0, ArgType1 uniform Arg1), (extract(Arg0, Index), extract(Arg1, Index)))
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index)))
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index)))
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index)))
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index)))
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index)))
#elif EMIT_FRIEND_DECLARATIONS
	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback();
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0);
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1);
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2);
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3);
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4);
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5);
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		friend extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6);
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback();
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0);
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1);
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2);
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3);
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4);
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5);
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		friend extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6);
#else
	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		extern "C" void FuncName ## _CppCallback() { CppCode }
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0) { CppCode }
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1) { CppCode }
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2) { CppCode }
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3) { CppCode }
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4) { CppCode }
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5) { CppCode }
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6) { CppCode }
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback() { CppCode }
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0) { CppCode }
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1) { CppCode }
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2) { CppCode }
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3) { CppCode }
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4) { CppCode }
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5) { CppCode }
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6) { CppCode }
#endif
