// Autogenerated by GenerateCallbackMacros.py, do not modify.

#include "CppInterop.h"

#ifdef ISPC
	#define _CppCallbackTemplate(FuncName, ArgDeclVarying, ArgDeclUniform, ArgFwd)	\
		inline void FuncName ArgDeclVarying	\
		{	\
			extern "C" void FuncName ## _CppCallback ArgDeclUniform;	\
			foreach_active (Index)	\
			{	\
				FuncName ## _CppCallback ArgFwd;	\
			}	\
		}

	#define _CppCallbackTemplate_RetVal(ReturnType, FuncName, ArgDeclVarying, ArgDeclUniform, ArgFwd)	\
		inline ReturnType varying FuncName ArgDeclVarying	\
		{	\
			extern "C" ReturnType uniform FuncName ## _CppCallback ArgDeclUniform;	\
			ReturnType varying ReturnValue;	\
			foreach_active (Index)	\
			{	\
				ReturnValue = insert(ReturnValue, Index, FuncName ## _CppCallback ArgFwd);	\
			}	\
		}

	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		_CppCallbackTemplate(FuncName, (), (), ())
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0), (ArgType0 uniform Arg0), (extract(Arg0, Index)))
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1), (ArgType0 uniform Arg0, ArgType1 uniform Arg1), (extract(Arg0, Index), extract(Arg1, Index)))
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index)))
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index)))
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index)))
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index)))
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index)))
	#define DefineCppCallback_8Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6, ArgType7 varying Arg7), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6, ArgType7 uniform Arg7), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index), extract(Arg7, Index)))
	#define DefineCppCallback_9Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		_CppCallbackTemplate(FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6, ArgType7 varying Arg7, ArgType8 varying Arg8), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6, ArgType7 uniform Arg7, ArgType8 uniform Arg8), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index), extract(Arg7, Index), extract(Arg8, Index)))
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (), (), ())
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0), (ArgType0 uniform Arg0), (extract(Arg0, Index)))
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1), (ArgType0 uniform Arg0, ArgType1 uniform Arg1), (extract(Arg0, Index), extract(Arg1, Index)))
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index)))
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index)))
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index)))
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index)))
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index)))
	#define DefineCppCallback_8Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6, ArgType7 varying Arg7), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6, ArgType7 uniform Arg7), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index), extract(Arg7, Index)))
	#define DefineCppCallback_9Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		_CppCallbackTemplate_RetVal(ReturnType, FuncName, (ArgType0 varying Arg0, ArgType1 varying Arg1, ArgType2 varying Arg2, ArgType3 varying Arg3, ArgType4 varying Arg4, ArgType5 varying Arg5, ArgType6 varying Arg6, ArgType7 varying Arg7, ArgType8 varying Arg8), (ArgType0 uniform Arg0, ArgType1 uniform Arg1, ArgType2 uniform Arg2, ArgType3 uniform Arg3, ArgType4 uniform Arg4, ArgType5 uniform Arg5, ArgType6 uniform Arg6, ArgType7 uniform Arg7, ArgType8 uniform Arg8), (extract(Arg0, Index), extract(Arg1, Index), extract(Arg2, Index), extract(Arg3, Index), extract(Arg4, Index), extract(Arg5, Index), extract(Arg6, Index), extract(Arg7, Index), extract(Arg8, Index)))
#elif defined(EMIT_FORWARD_DECLARATIONS)
	#ifdef DefineCppCallback_0Arg
		#undef DefineCppCallback_0Arg
	#endif
	#ifdef DefineCppCallback_1Arg
		#undef DefineCppCallback_1Arg
	#endif
	#ifdef DefineCppCallback_2Arg
		#undef DefineCppCallback_2Arg
	#endif
	#ifdef DefineCppCallback_3Arg
		#undef DefineCppCallback_3Arg
	#endif
	#ifdef DefineCppCallback_4Arg
		#undef DefineCppCallback_4Arg
	#endif
	#ifdef DefineCppCallback_5Arg
		#undef DefineCppCallback_5Arg
	#endif
	#ifdef DefineCppCallback_6Arg
		#undef DefineCppCallback_6Arg
	#endif
	#ifdef DefineCppCallback_7Arg
		#undef DefineCppCallback_7Arg
	#endif
	#ifdef DefineCppCallback_8Arg
		#undef DefineCppCallback_8Arg
	#endif
	#ifdef DefineCppCallback_9Arg
		#undef DefineCppCallback_9Arg
	#endif
	#ifdef DefineCppCallback_0Arg_RetVal
		#undef DefineCppCallback_0Arg_RetVal
	#endif
	#ifdef DefineCppCallback_1Arg_RetVal
		#undef DefineCppCallback_1Arg_RetVal
	#endif
	#ifdef DefineCppCallback_2Arg_RetVal
		#undef DefineCppCallback_2Arg_RetVal
	#endif
	#ifdef DefineCppCallback_3Arg_RetVal
		#undef DefineCppCallback_3Arg_RetVal
	#endif
	#ifdef DefineCppCallback_4Arg_RetVal
		#undef DefineCppCallback_4Arg_RetVal
	#endif
	#ifdef DefineCppCallback_5Arg_RetVal
		#undef DefineCppCallback_5Arg_RetVal
	#endif
	#ifdef DefineCppCallback_6Arg_RetVal
		#undef DefineCppCallback_6Arg_RetVal
	#endif
	#ifdef DefineCppCallback_7Arg_RetVal
		#undef DefineCppCallback_7Arg_RetVal
	#endif
	#ifdef DefineCppCallback_8Arg_RetVal
		#undef DefineCppCallback_8Arg_RetVal
	#endif
	#ifdef DefineCppCallback_9Arg_RetVal
		#undef DefineCppCallback_9Arg_RetVal
	#endif
	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		extern "C" void FuncName ## _CppCallback();
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0);
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1);
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2);
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3);
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4);
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5);
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6);
	#define DefineCppCallback_8Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7);
	#define DefineCppCallback_9Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7, ArgType8 Arg8);
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback();
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0);
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1);
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2);
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3);
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4);
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5);
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6);
	#define DefineCppCallback_8Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7);
	#define DefineCppCallback_9Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7, ArgType8 Arg8);
#elif defined(EMIT_FRIEND_DECLARATIONS)
	#ifdef DefineCppCallback_0Arg
		#undef DefineCppCallback_0Arg
	#endif
	#ifdef DefineCppCallback_1Arg
		#undef DefineCppCallback_1Arg
	#endif
	#ifdef DefineCppCallback_2Arg
		#undef DefineCppCallback_2Arg
	#endif
	#ifdef DefineCppCallback_3Arg
		#undef DefineCppCallback_3Arg
	#endif
	#ifdef DefineCppCallback_4Arg
		#undef DefineCppCallback_4Arg
	#endif
	#ifdef DefineCppCallback_5Arg
		#undef DefineCppCallback_5Arg
	#endif
	#ifdef DefineCppCallback_6Arg
		#undef DefineCppCallback_6Arg
	#endif
	#ifdef DefineCppCallback_7Arg
		#undef DefineCppCallback_7Arg
	#endif
	#ifdef DefineCppCallback_8Arg
		#undef DefineCppCallback_8Arg
	#endif
	#ifdef DefineCppCallback_9Arg
		#undef DefineCppCallback_9Arg
	#endif
	#ifdef DefineCppCallback_0Arg_RetVal
		#undef DefineCppCallback_0Arg_RetVal
	#endif
	#ifdef DefineCppCallback_1Arg_RetVal
		#undef DefineCppCallback_1Arg_RetVal
	#endif
	#ifdef DefineCppCallback_2Arg_RetVal
		#undef DefineCppCallback_2Arg_RetVal
	#endif
	#ifdef DefineCppCallback_3Arg_RetVal
		#undef DefineCppCallback_3Arg_RetVal
	#endif
	#ifdef DefineCppCallback_4Arg_RetVal
		#undef DefineCppCallback_4Arg_RetVal
	#endif
	#ifdef DefineCppCallback_5Arg_RetVal
		#undef DefineCppCallback_5Arg_RetVal
	#endif
	#ifdef DefineCppCallback_6Arg_RetVal
		#undef DefineCppCallback_6Arg_RetVal
	#endif
	#ifdef DefineCppCallback_7Arg_RetVal
		#undef DefineCppCallback_7Arg_RetVal
	#endif
	#ifdef DefineCppCallback_8Arg_RetVal
		#undef DefineCppCallback_8Arg_RetVal
	#endif
	#ifdef DefineCppCallback_9Arg_RetVal
		#undef DefineCppCallback_9Arg_RetVal
	#endif
	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		friend void FuncName ## _CppCallback();
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0);
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1);
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2);
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3);
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4);
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5);
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6);
	#define DefineCppCallback_8Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7);
	#define DefineCppCallback_9Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		friend void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7, ArgType8 Arg8);
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		friend ReturnType FuncName ## _CppCallback();
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0);
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1);
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2);
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3);
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4);
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5);
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6);
	#define DefineCppCallback_8Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7);
	#define DefineCppCallback_9Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		friend ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7, ArgType8 Arg8);
#else
	#ifdef DefineCppCallback_0Arg
		#undef DefineCppCallback_0Arg
	#endif
	#ifdef DefineCppCallback_1Arg
		#undef DefineCppCallback_1Arg
	#endif
	#ifdef DefineCppCallback_2Arg
		#undef DefineCppCallback_2Arg
	#endif
	#ifdef DefineCppCallback_3Arg
		#undef DefineCppCallback_3Arg
	#endif
	#ifdef DefineCppCallback_4Arg
		#undef DefineCppCallback_4Arg
	#endif
	#ifdef DefineCppCallback_5Arg
		#undef DefineCppCallback_5Arg
	#endif
	#ifdef DefineCppCallback_6Arg
		#undef DefineCppCallback_6Arg
	#endif
	#ifdef DefineCppCallback_7Arg
		#undef DefineCppCallback_7Arg
	#endif
	#ifdef DefineCppCallback_8Arg
		#undef DefineCppCallback_8Arg
	#endif
	#ifdef DefineCppCallback_9Arg
		#undef DefineCppCallback_9Arg
	#endif
	#ifdef DefineCppCallback_0Arg_RetVal
		#undef DefineCppCallback_0Arg_RetVal
	#endif
	#ifdef DefineCppCallback_1Arg_RetVal
		#undef DefineCppCallback_1Arg_RetVal
	#endif
	#ifdef DefineCppCallback_2Arg_RetVal
		#undef DefineCppCallback_2Arg_RetVal
	#endif
	#ifdef DefineCppCallback_3Arg_RetVal
		#undef DefineCppCallback_3Arg_RetVal
	#endif
	#ifdef DefineCppCallback_4Arg_RetVal
		#undef DefineCppCallback_4Arg_RetVal
	#endif
	#ifdef DefineCppCallback_5Arg_RetVal
		#undef DefineCppCallback_5Arg_RetVal
	#endif
	#ifdef DefineCppCallback_6Arg_RetVal
		#undef DefineCppCallback_6Arg_RetVal
	#endif
	#ifdef DefineCppCallback_7Arg_RetVal
		#undef DefineCppCallback_7Arg_RetVal
	#endif
	#ifdef DefineCppCallback_8Arg_RetVal
		#undef DefineCppCallback_8Arg_RetVal
	#endif
	#ifdef DefineCppCallback_9Arg_RetVal
		#undef DefineCppCallback_9Arg_RetVal
	#endif
	#define DefineCppCallback_0Arg(FuncName, CppCode)	\
		extern "C" void FuncName ## _CppCallback() CppCode
	#define DefineCppCallback_1Arg(FuncName, ArgType0, Arg0, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0) CppCode
	#define DefineCppCallback_2Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1) CppCode
	#define DefineCppCallback_3Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2) CppCode
	#define DefineCppCallback_4Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3) CppCode
	#define DefineCppCallback_5Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4) CppCode
	#define DefineCppCallback_6Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5) CppCode
	#define DefineCppCallback_7Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6) CppCode
	#define DefineCppCallback_8Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7) CppCode
	#define DefineCppCallback_9Arg(FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		extern "C" void FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7, ArgType8 Arg8) CppCode
	#define DefineCppCallback_0Arg_RetVal(ReturnType, FuncName, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback() CppCode
	#define DefineCppCallback_1Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0) CppCode
	#define DefineCppCallback_2Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1) CppCode
	#define DefineCppCallback_3Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2) CppCode
	#define DefineCppCallback_4Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3) CppCode
	#define DefineCppCallback_5Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4) CppCode
	#define DefineCppCallback_6Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5) CppCode
	#define DefineCppCallback_7Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6) CppCode
	#define DefineCppCallback_8Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7) CppCode
	#define DefineCppCallback_9Arg_RetVal(ReturnType, FuncName, ArgType0, Arg0, ArgType1, Arg1, ArgType2, Arg2, ArgType3, Arg3, ArgType4, Arg4, ArgType5, Arg5, ArgType6, Arg6, ArgType7, Arg7, ArgType8, Arg8, CppCode)	\
		extern "C" ReturnType FuncName ## _CppCallback(ArgType0 Arg0, ArgType1 Arg1, ArgType2 Arg2, ArgType3 Arg3, ArgType4 Arg4, ArgType5 Arg5, ArgType6 Arg6, ArgType7 Arg7, ArgType8 Arg8) CppCode
#endif
