#!/usr/bin/python

global VariantCount, File
VariantCount = 10
File = open('CppCallbackMacros.h', 'w')

def EmitCallbackMacrosISPCSide(bUseReturnType):
	for Count in range(VariantCount):
		MacroArgs = ''
		ArgDeclVarying = '('
		ArgDeclUniform = '('
		ArgFwd = '('
		for Index in range(Count):
			MacroArgs += 'ArgType{0}, Arg{0}, '.format(Index)
			ArgDeclVarying += 'ArgType{0} varying Arg{0}'.format(Index)
			ArgDeclUniform += 'ArgType{0} uniform Arg{0}'.format(Index)
			ArgFwd += 'extract(Arg{0}, Index)'.format(Index)
			if Index != Count - 1:
				ArgDeclVarying += ', '
				ArgDeclUniform += ', '
				ArgFwd += ', '
		ArgDeclVarying += ')'
		ArgDeclUniform += ')'
		ArgFwd += ')'
		File.write(r'''	#define DefineCppCallback_{0}Arg{1}({2}FuncName, {3}CppCode)	\
		_CppCallbackTemplate{1}({2}FuncName, {4}, {5}, {6})
'''.format(
			Count,
			'_RetVal' if bUseReturnType else '',
			'ReturnType, ' if bUseReturnType else '',
			MacroArgs,
			ArgDeclVarying,
			ArgDeclUniform,
			ArgFwd))

def EmitCallbackMacrosUndefsCppSide(bUseReturnType):
	for Count in range(VariantCount):
		MacroArgs = ''
		ArgDecl = ''
		for Index in range(Count):
			MacroArgs += 'ArgType{0}, Arg{0}, '.format(Index)
			ArgDecl += 'ArgType{0} Arg{0}'.format(Index)
			if Index != Count - 1:
				ArgDecl += ', '
		ArgDecl += ''
		File.write(r'''	#ifdef DefineCppCallback_{0}Arg{1}
		#undef DefineCppCallback_{0}Arg{1}
	#endif
'''.format(
			Count,
			'_RetVal' if bUseReturnType else ''))

def EmitCallbackMacrosCppSide(bUseReturnType, bFriend, bDeclarations):
	for Count in range(VariantCount):
		MacroArgs = ''
		ArgDecl = ''
		for Index in range(Count):
			MacroArgs += 'ArgType{0}, Arg{0}, '.format(Index)
			ArgDecl += 'ArgType{0} Arg{0}'.format(Index)
			if Index != Count - 1:
				ArgDecl += ', '
		ArgDecl += ''
		File.write(r'''	#define DefineCppCallback_{0}Arg{1}({2}FuncName, {3}CppCode)	\
		{4} {5} FuncName ## _CppCallback({6}){7}
'''.format(
			Count,
			'_RetVal' if bUseReturnType else '',
			'ReturnType, ' if bUseReturnType else '',
			MacroArgs,
			'friend' if bFriend else 'extern "C"',
			'ReturnType' if bUseReturnType else 'void',
			ArgDecl,
			';' if bDeclarations else ' CppCode'))

File.write(r'''// Autogenerated by GenerateCallbackMacros.py, do not modify.

#include "CppInterop.h"

#ifdef ISPC
	#define _CppCallbackTemplate(FuncName, ArgDeclVarying, ArgDeclUniform, ArgFwd)	\
		inline void FuncName ArgDeclVarying	\
		{	\
			extern "C" void FuncName ## _CppCallback ArgDeclUniform;	\
			foreach_active (Index)	\
			{	\
				FuncName ## _CppCallback ArgFwd;	\
			}	\
		}

	#define _CppCallbackTemplate_RetVal(ReturnType, FuncName, ArgDeclVarying, ArgDeclUniform, ArgFwd)	\
		inline ReturnType varying FuncName ArgDeclVarying	\
		{	\
			extern "C" ReturnType uniform FuncName ## _CppCallback ArgDeclUniform;	\
			ReturnType varying ReturnValue;	\
			foreach_active (Index)	\
			{	\
				ReturnValue = insert(ReturnValue, Index, FuncName ## _CppCallback ArgFwd);	\
			}	\
		}

''')

EmitCallbackMacrosISPCSide(False)
EmitCallbackMacrosISPCSide(True)

File.write(r'''#elif defined(EMIT_FORWARD_DECLARATIONS)
''')

EmitCallbackMacrosUndefsCppSide(False)
EmitCallbackMacrosUndefsCppSide(True)

EmitCallbackMacrosCppSide(False, False, True)
EmitCallbackMacrosCppSide(True, False, True)

File.write(r'''#elif defined(EMIT_FRIEND_DECLARATIONS)
''')

EmitCallbackMacrosUndefsCppSide(False)
EmitCallbackMacrosUndefsCppSide(True)

EmitCallbackMacrosCppSide(False, True, True)
EmitCallbackMacrosCppSide(True, True, True)

File.write(r'''#else
''')

EmitCallbackMacrosUndefsCppSide(False)
EmitCallbackMacrosUndefsCppSide(True)

EmitCallbackMacrosCppSide(False, False, False)
EmitCallbackMacrosCppSide(True, False, False)

File.write(r'''#endif
''')